'use client'
import { useEffect } from 'react';
import '../../globals.css';
import '../dist/css/adminlte.css';
import Navbar from '@/components/Admin/navbar';
import Footer from '@/components/Admin/footer';
import Sidebar from '@/components/Admin/sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    import('../dist/js/adminlte.js');
  }, []);
  return (
    <html className="hold-transition sidebar-mini layout-fixed" lang="en">
      <body className="layout-fixed sidebar-expand-lg bg-body-tertiary">
        <div className="app-wrapper">
          <Navbar />
          <Sidebar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
