'use client'
import '../../globals.css';
import { SessionProvider } from "next-auth/react"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex items-center bg-white ">
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </div>
      </body>
    </html>
  )
}
