// import '';

export const metadata = {
    title: 'Zuhot - Đặt ghế',
    description: 'Generated by create next app',
}

export default function BookSeatLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        { children }
    )
}
