import './../globals.css';
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar';
const inter = Inter({ subsets: ['latin'] })
import logo from "../logo.png";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link
  rel="icon"
  href="/_next/image?url=%2Fassert%2Fimg%2Flogo.png&w=256&q=75"
  sizes='32x32'
/>
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
